trigger:
- main  # Trigger the pipeline on changes to 'main'

pool:
  vmImage: ubuntu-latest  # Using Ubuntu as the base image

steps:
- script: echo "Running the pipeline"
  displayName: 'Run Pre-build Steps'

# Ensure Git config is set up for commit and push
- script: |
    git config --global user.email "youremail@example.com"
    git config --global user.name "Your Name"
  displayName: 'Set Git User Information'

# Verify if there are changes and commit them
- script: |
    echo "Checking Git status..."
    git status  # Check if there are any changes
    git diff     # Show differences before committing
    
    # Stage all modified files
    git add .    # Add all modified files to the staging area

    # Commit changes if there are any, otherwise skip
    if ! git diff --cached --quiet; then
      git commit -m "Auto commit from Azure DevOps pipeline"
      echo "Changes committed."
    else
      echo "No changes to commit."
    fi
    
    # Push changes to the GitHub repository (ensure correct branch)
    git remote -v  # Check the remote repository URL
    git push origin main  # Replace 'main' with your branch if different
  displayName: 'Commit and Push Changes to GitHub'

# List build directory to ensure files are being generated correctly
- script: |
    ls -la $(Build.ArtifactStagingDirectory)  # Check if program files are generated
  displayName: 'List Build Directory'


