trigger:
  branches:
    include:
      - main  # or your default branch (e.g., master)

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Checkout@2
  displayName: 'Checkout code from GitHub'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Use the appropriate version for your project
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: Restore@1
  inputs:
    projectFile: '**/*.csproj'  # Path to your .csproj file

- task: Build@1
  inputs:
    solution: '**/*.sln'  # Path to your .sln file
    buildConfiguration: $(buildConfiguration)

- task: Publish@1
  inputs:
    publishWebProjects: false
    solution: '**/*.sln'
    zipAfterPublish: false
    buildConfiguration: $(buildConfiguration)
    outputPath: '$(Build.ArtifactStagingDirectory)'

# Commit and push changes (if necessary)
- script: |
    git config --global user.email "youremail@example.com"
    git config --global user.name "Your Name"
    git add .
    git commit -m "Auto commit from Azure Pipeline"
    git push origin main  # or the branch you're working with
  displayName: 'Commit and Push changes back to GitHub'
