trigger:
- main  # Trigger the pipeline on changes to 'main'

pool:
  vmImage: ubuntu-latest  # Running the pipeline on Ubuntu

steps:
- checkout: self  # Checkout code from GitHub repository

# Build process (example)
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
  displayName: 'Build .NET Core Project'

# Optional: Generate or modify files here, if needed
# For example, modify or generate output in Program.cs or other files

# Step: Check for changes and only commit if necessary
- script: |
    git diff --quiet || echo "Changes detected"
    git add .  # Add all changes (if any)
    if ! git diff --cached --quiet; then
      git commit -m "Update modified files from pipeline"
      git push origin main  # Push changes to GitHub (ensure 'main' is your default branch)
    else
      echo "No changes to commit"
    fi
  displayName: 'Commit and Push Changes to GitHub (if any)'

# Finish the pipeline
